# Site
name: "in*die zine"
title: "in*die zine"
description: "An indie rpg zine"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
  # google_analytics: ''
  # disqus: ''
  # mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
domain: www.indiezine.games
url: https://www.indiezine.games

# Authors
authors:
  voen:
    name: Voen
    display_name: Voen
      # gravatar: 
    email: voen.octuro@gmail.com
      # web: https://www.oakenboro.blog
    twitter: https://twitter.com/oakenboro
    description: "Somtimes writes or writes about RPGs"
  dmg:
    name: D.M.G./Gharmey Hapscoy
    display_name: D.M.G./Gharmey Hapscoy
    avatar: assets/images/avatars/dmg-avatar.png
    web: https://twitter.com/Sector8TTRPG
    twitter: https://twitter.com/DMG_Tha_Whale
    description: "Hi! I'm D.M.G., I work on pixelart and tabletop RPGs, mostly sci-fi and fantasy!"
  librivore42:
    name: Librivore42
    display_name: Librivore42
    avatar: assets/images/avatars/librivore42-avatar.png
    description: "Librivore42 is a hobbyist writer, crafter and game dev-er who believes in learning by doing, and trying every skill at least once."
  nicosantagoy:
    name: Nico
    display_name: san_tagoy
      # web: https://tagoymakes.com/
    twitter: https://twitter.com/san_tagoy
    description: "Writer of Tabletop RPG things and eager to learn just about anything."
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
  # adsense-data-ad-client: ""
  # adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
